### ISSUE TITLE
Results are different from blockchain.com

### ISSUE THREAD

**Issue by GE0L0GIST** [circulosmeos/bitcoin-in-tiny-pieces#3]
Hello,

I want to convert script pub key into bitcoin address.

I'm using script pub key from this transaction (tx hash) on blockchair.com: a070eda356c87a7af9bff22eab3b3c38460605eb00938c84a86a1d6d3c608078

Link:
https://blockchair.com/bitcoin/transaction/a070eda356c87a7af9bff22eab3b3c38460605eb00938c84a86a1d6d3c608078

It has next script pub key: fb2737b020d6c0555513092f7f004976c4c18c53
According to blockchair.com corresponding address is: 76a914fb2737b020d6c0555513092f7f004976c4c18c5388ac

But when I'm using bitcoin-in-tiny-pieces I have different addresses based on script pub key:

Uncompressed public key:
key_hash = 	891b647d941b887ad4061cd22651d4b52682b5c8
checksum = 	591f2031292a0e4144cf6c7659d87c158661b19396c890c2602ba87de71a3c7c
key_hash + checksum = 	00891b647d941b887ad4061cd22651d4b52682b5c8 591f2031
bitcoin address = 	1DVxPYn7t1J1U1MoLM8gCXZ17jCdPGe5je

Compressed public key:
key_hash = 	c02f664efb9341695f584eaa886ae27e59070c19
checksum = 	7544f96a8b280ddc0301213c793831af4c6dd6994d982f3994a845dece56f0d9
key_hash + checksum = 	00c02f664efb9341695f584eaa886ae27e59070c19 7544f96a
bitcoin address = 	1JXBXDYofUjwV1CWLDMcY8jrJt4n3q8xaV

Hybrid public key:
key_hash = 	d6095f3e929ce503d6d47cb066d78b2b187e27a5
checksum = 	d8030cd715ccdbe308b45bbc64460aa0099dec113d96986383c1be12459d7e5e
key_hash + checksum = 	00d6095f3e929ce503d6d47cb066d78b2b187e27a5 d8030cd7
bitcoin address = 	1LWiqEX1PoyXHc7XMWeE2wyfMsYY8rYhHG

Non of them correspond to the address from blockchair.com. Can you please advice what am I doing wrong and why addresses from bitcoin-in-tiny-pieces are different from blockchair.com?

**Comment by circulosmeos** [comment]
Hi @GE0L0GIST ,
As far as I can see, for the provided tx
`a070eda356c87a7af9bff22eab3b3c38460605eb00938c84a86a1d6d3c608078` [1]
the value you provide as address:
`76a914fb2737b020d6c0555513092f7f004976c4c18c5388ac` [2]
is really the hexadecimal representation of the output script:
`OP_DUP OP_HASH160 fb2737b020d6c0555513092f7f004976c4c18c53 OP_EQUALVERIFY OP_CHECKSIG` [3]
( note for this that [2] contains the bitcoin address stated in [3] (`fb27...8c53`) )
So this `76a9...88ac` is not a valid bitcoin address.

Also, the value `fb27...8c53` referenced in the script is not a valid address, as it is a hash (SHA-256 + RIPEMD-160) of the public key.

Refer for example to https://academy.bit2me.com/en/que-es-bitcoin-script/
